Revert "Merge pull request #391 from WebPlatformForEmbedded/fix_cmake_find_scripts"
This reverts commit d07f3a5c8fe32c3671a1881d179ff55e30bd6192, reversing
changes made to 18d7ed73f29fb073d26441048caab0cfdc2ebaaf.

These changes break regular builds (BR) on RPI2/3 (and probably more) with the following error message during build:

In file included from /home/wouter/workspace/buildroot-rpi2/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/playready/drmtypes.h:13:0,
                 from ../Source/WebCore/platform/graphics/gstreamer/eme/PlayreadySession.h:27,
                 from /home/wouter/workspace/buildroot-rpi2/output/build/wpewebkit-custom/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:153:
/home/wouter/workspace/buildroot-rpi2/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/playready/drmcompiler.h:418:5: warning: "DRM_64BIT_TARGET" is not defined [-Wundef]
 #if DRM_64BIT_TARGET
     ^
/home/wouter/workspace/buildroot-rpi2/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/playready/drmcompiler.h:563:5: warning: "DBG" is not defined [-Wundef]
 #if DBG
     ^
In file included from /home/wouter/workspace/buildroot-rpi2/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/playready/drmtypes.h:14:0,
                 from ../Source/WebCore/platform/graphics/gstreamer/eme/PlayreadySession.h:27,
                 from /home/wouter/workspace/buildroot-rpi2/output/build/wpewebkit-custom/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:153:
/home/wouter/workspace/buildroot-rpi2/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/playready/drmint64.h:26:5: warning: "DRM_64BIT_TARGET" is not defined [-Wundef]
 #if DRM_64BIT_TARGET
     ^
In file included from ../Source/WebCore/platform/graphics/gstreamer/eme/PlayreadySession.h:27:0,
                 from /home/wouter/workspace/buildroot-rpi2/output/build/wpewebkit-custom/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:153:
/home/wouter/workspace/buildroot-rpi2/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/playready/drmtypes.h:98:5: warning: "DRM_64BIT_TARGET" is not defined [-Wundef]
 #if DRM_64BIT_TARGET
     ^
/home/wouter/workspace/buildroot-rpi2/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/playready/drmtypes.h:107:54: warning: "DRM_MSC_VER" is not defined [-Wundef]
 #if defined(__cplusplus) && !defined(_PREFAST_) && ( DRM_MSC_VER >= 1400 )
                                                      ^
In file included from /home/wouter/workspace/buildroot-rpi2/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/playready/drmerr.h:13:0,
                 from /home/wouter/workspace/buildroot-rpi2/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/playready/drmcommon.h:12,
                 from ../Source/WebCore/platform/graphics/gstreamer/eme/PlayreadySession.h:28,
                 from /home/wouter/workspace/buildroot-rpi2/output/build/wpewebkit-custom/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:153:
/home/wouter/workspace/buildroot-rpi2/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/playready/drmdebug.h:13:22: fatal error: oemdebug.h: No such file or directory
compilation terminated.
[3625/4499] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/gstreamer/mse/PlaybackPipeline.cpp.o
ninja: build stopped: subcommand failed.
package/pkg-generic.mk:216: recipe for target '/home/wouter/workspace/buildroot-rpi2/output/build/wpewebkit-custom/.stamp_built' failed
make[1]: *** [/home/wouter/workspace/buildroot-rpi2/output/build/wpewebkit-custom/.stamp_built] Error 1
Makefile:79: recipe for target '_all' failed
make: *** [_all] Error 2

Seems like a define gets messed up somewhere when doing the PlayReady cmake finds. Please fix and try again.