[dom]: fix: build issue from gcc 9.2
 error: expected ';' before 'if'

Above error caused building from gcc 9.2, is fixed

Signed-off-by: Moorthy Baskar <moorthy.baskaravenkatraman-sambamoorthy@linaro.org>