WebInspector: Can't open a new tab: Uncaught Exception: TypeError: this.isNewTabWithTypeAllowed is not a function https://bugs.webkit.org/show_bug.cgi?id=152471
Reviewed by Timothy Hatcher.

* UserInterface/Base/Main.js:
(WebInspector._updateNewTabButtonState):
Don't use arrow functions because of https://webkit.org/b/152497 "Arrow functions: 'this' isn't lexically bound"


git-svn-id: http://svn.webkit.org/repository/webkit/trunk@194360 268f45cc-cd09-0410-ab3c-d52691b4dbfc