REGRESSION (r206973): Running "webkit-patch suggest-reviewers" throws an AttributeError: 'NoneType' object has no attribute 'full_name' https://bugs.webkit.org/show_bug.cgi?id=163478
Reviewed by Daniel Bates.

Handle a None other in Contributor.__eq__.

* Scripts/webkitpy/common/config/committers.py:
(Contributor.__eq__):


git-svn-id: http://svn.webkit.org/repository/webkit/trunk@207370 268f45cc-cd09-0410-ab3c-d52691b4dbfc