Move Vector HashTraits to HashTraits.h to fix GCC build https://bugs.webkit.org/show_bug.cgi?id=205540
Reviewed by Zalan Bujtas.

Source/WebCore:

* contentextensions/DFAMinimizer.cpp:

ActionKey HashTrait claims that emptyValueIsZero. Now with Vector HashTrait having emptyValueIsZero too
HashMap<ActionKey, Vector<>> started taking the optimized path.

However ActionKey empty value wasn't actually zero because Empty enum value wasn't 0.

Source/WTF:

GCC is stricter than LLVM with partial specializations

Error: partial specialization of struct WTF::HashTraits<WTF::Vector<U, otherCapacity, WTF::CrashOnOverflow, 16> >
after instantiation of struct WTF::HashTraits<WTF::Vector<WTF::String> >

* wtf/HashTraits.h:
* wtf/VectorHash.h:


git-svn-id: http://svn.webkit.org/repository/webkit/trunk@253864 268f45cc-cd09-0410-ab3c-d52691b4dbfc