css-contain category missing from CSSProperties.json https://bugs.webkit.org/show_bug.cgi?id=224990
Patch by Tyler Wilcock <twilco.o@protonmail.com> on 2021-04-25
Reviewed by Darin Adler.

* css/CSSProperties.json:
Add missing css-contain category to avoid style lint errors.  Example
error:

ERROR: Source/WebCore/css/CSSProperties.json:0:  property "contain" has category "css-contain" which is not in the set of categories.  [json/syntax] [5]

git-svn-id: http://svn.webkit.org/repository/webkit/trunk@276565 268f45cc-cd09-0410-ab3c-d52691b4dbfc