REGRESSION (r186976): Windows build broke due to missing definition of M_PI
Attempt to fix the following build failure:

    PathUtilities.cpp(182): error C2065: 'M_PI' : undeclared identifier [...\Source\WebCore\WebCore.vcxproj\WebCore.vcxproj]

* platform/graphics/PathUtilities.cpp: Include <wtf/MathExtras.h>.

git-svn-id: http://svn.webkit.org/repository/webkit/trunk@186990 268f45cc-cd09-0410-ab3c-d52691b4dbfc