REGRESSION (r186976): Use piFloat instead of M_PI
Attempt to fix the following build failure:

    PathUtilities.cpp(183): error C2065: 'M_PI' : undeclared identifier [...\Source\WebCore\WebCore.vcxproj\WebCore.vcxproj]

* platform/graphics/PathUtilities.cpp:
(WebCore::walkGraphAndExtractPolygon): Use piFloat since M_PI is
not defined on Windows.

git-svn-id: http://svn.webkit.org/repository/webkit/trunk@186991 268f45cc-cd09-0410-ab3c-d52691b4dbfc